Repository davidfer1112/tallergit, pull requests merged in 2024-08, with the labels that each got.

#2 Feature: funcion buenas tardes
  davidpeje/davidpeje
Labels: bug, documentation, duplicate

#3 Feature: Hola buenos días
  alejandroC/alejandroC.cpp
Labels: documentation

#4 Feature: Feliz dia
  SamOso/SamOso.cpp
Labels: enhancement

#5 Develop
  SamOso/SamOso.cpp
  davidpeje/davidpeje
Labels: bug, documentation, duplicate, enhancement
